version: '3.8'

services:
  # Servicio API Backend con OpenAI
  api-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: openai-api
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=
      - PORT=8000
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - chat-network

  # Servicio Chainlit Frontend
  chainlit-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chainlit-app
    ports:
      - "8080:8080"
    environment:
      - API_BACKEND_URL=http://api-backend:8000
      - CHAINLIT_PORT=8080
    depends_on:
      - api-backend
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge